version: '3.6'
services:
  #browser
  firefox:
    image: selenium/standalone-firefox
    ports:
      - 127.0.0.1:8888:4444
  # messagebroker
  redis:
    image: redis
    ports:
      - 127.0.0.1:8001:6379
  web:
    build: .
    ports:
      - 127.0.0.1:8000:5000
    