project_sub = {"Akshaya Tango": "Tango",
               "Akshaya Republic": "Republic",
               "Akshaya Today": 'Today',
               "Akshaya OrlandO":'OrlandO',
               "Akshaya Earth":'Earth',
               "Akshaya Shanti":'Shanti',
               "Akshaya Poongavanam":'Poongavanam',
              "Thoraipakkam": 'Tango',
          "Perungudi":'Tango',
          "Pallavaram":'Tango',
          "OMR":'Today',
          "Kelambakkam":'Today',
          "Sholinganallur":'Tango',
          "Navalur":'Today',
         }