name: flask_applcation
on:
 push:
   branches:
     - "release_2.1"
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          echo Hello there!